<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : response.proto
 */
/**
 * Protobuf message : ChannelStatsResponse
 */
class ChannelStatsResponse extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * channels repeated message = 1
     *
     * @var \Protobuf\Collection<\Bitrix\Pull\Protobuf\ChannelStats>
     */
    protected $channels = null;
    /**
     * Check if 'channels' has a value
     *
     * @return bool
     */
    public function hasChannelsList()
    {
    }
    /**
     * Get 'channels' value
     *
     * @return \Protobuf\Collection<\Bitrix\Pull\Protobuf\ChannelStats>
     */
    public function getChannelsList()
    {
    }
    /**
     * Set 'channels' value
     *
     * @param \Protobuf\Collection<\Bitrix\Pull\Protobuf\ChannelStats> $value
     */
    public function setChannelsList(\Protobuf\Collection $value = null)
    {
    }
    /**
     * Add a new element to 'channels'
     *
     * @param \Bitrix\Pull\Protobuf\ChannelStats $value
     */
    public function addChannels(\Bitrix\Pull\Protobuf\ChannelStats $value)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}