<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : response.proto
 */
/**
 * Protobuf message : ChannelStats
 */
class ChannelStats extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * id optional bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $id = null;
    /**
     * isPrivate optional bool = 2
     *
     * @var bool
     */
    protected $isPrivate = null;
    /**
     * isOnline optional bool = 3
     *
     * @var bool
     */
    protected $isOnline = null;
    /**
     * Check if 'id' has a value
     *
     * @return bool
     */
    public function hasId()
    {
    }
    /**
     * Get 'id' value
     *
     * @return \Protobuf\Stream
     */
    public function getId()
    {
    }
    /**
     * Set 'id' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setId($value = null)
    {
    }
    /**
     * Check if 'isPrivate' has a value
     *
     * @return bool
     */
    public function hasIsPrivate()
    {
    }
    /**
     * Get 'isPrivate' value
     *
     * @return bool
     */
    public function getIsPrivate()
    {
    }
    /**
     * Set 'isPrivate' value
     *
     * @param bool $value
     */
    public function setIsPrivate($value = null)
    {
    }
    /**
     * Check if 'isOnline' has a value
     *
     * @return bool
     */
    public function hasIsOnline()
    {
    }
    /**
     * Get 'isOnline' value
     *
     * @return bool
     */
    public function getIsOnline()
    {
    }
    /**
     * Set 'isOnline' value
     *
     * @param bool $value
     */
    public function setIsOnline($value = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}