<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : request.proto
 */
/**
 * Protobuf message : IncomingMessage
 */
class IncomingMessage extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * receivers repeated message = 1
     *
     * @var \Protobuf\Collection<\Bitrix\Pull\Protobuf\Receiver>
     */
    protected $receivers = null;
    /**
     * sender optional message = 2
     *
     * @var \Bitrix\Pull\Protobuf\Sender
     */
    protected $sender = null;
    /**
     * body optional string = 3
     *
     * @var string
     */
    protected $body = null;
    /**
     * expiry optional uint32 = 4
     *
     * @var int
     */
    protected $expiry = null;
    /**
     * type optional string = 5
     *
     * @var string
     */
    protected $type = null;
    /**
     * Check if 'receivers' has a value
     *
     * @return bool
     */
    public function hasReceiversList()
    {
    }
    /**
     * Get 'receivers' value
     *
     * @return \Protobuf\Collection<\Bitrix\Pull\Protobuf\Receiver>
     */
    public function getReceiversList()
    {
    }
    /**
     * Set 'receivers' value
     *
     * @param \Protobuf\Collection<\Bitrix\Pull\Protobuf\Receiver> $value
     */
    public function setReceiversList(\Protobuf\Collection $value = null)
    {
    }
    /**
     * Add a new element to 'receivers'
     *
     * @param \Bitrix\Pull\Protobuf\Receiver $value
     */
    public function addReceivers(\Bitrix\Pull\Protobuf\Receiver $value)
    {
    }
    /**
     * Check if 'sender' has a value
     *
     * @return bool
     */
    public function hasSender()
    {
    }
    /**
     * Get 'sender' value
     *
     * @return \Bitrix\Pull\Protobuf\Sender
     */
    public function getSender()
    {
    }
    /**
     * Set 'sender' value
     *
     * @param \Bitrix\Pull\Protobuf\Sender $value
     */
    public function setSender(\Bitrix\Pull\Protobuf\Sender $value = null)
    {
    }
    /**
     * Check if 'body' has a value
     *
     * @return bool
     */
    public function hasBody()
    {
    }
    /**
     * Get 'body' value
     *
     * @return string
     */
    public function getBody()
    {
    }
    /**
     * Set 'body' value
     *
     * @param string $value
     */
    public function setBody($value = null)
    {
    }
    /**
     * Check if 'expiry' has a value
     *
     * @return bool
     */
    public function hasExpiry()
    {
    }
    /**
     * Get 'expiry' value
     *
     * @return int
     */
    public function getExpiry()
    {
    }
    /**
     * Set 'expiry' value
     *
     * @param int $value
     */
    public function setExpiry($value = null)
    {
    }
    /**
     * Check if 'type' has a value
     *
     * @return bool
     */
    public function hasType()
    {
    }
    /**
     * Get 'type' value
     *
     * @return string
     */
    public function getType()
    {
    }
    /**
     * Set 'type' value
     *
     * @param string $value
     */
    public function setType($value = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}