<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : response.proto
 */
/**
 * Protobuf message : OutgoingMessage
 */
class OutgoingMessage extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * id optional bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $id = null;
    /**
     * body optional string = 2
     *
     * @var string
     */
    protected $body = null;
    /**
     * expiry optional uint32 = 3
     *
     * @var int
     */
    protected $expiry = null;
    /**
     * created optional fixed32 = 4
     *
     * @var int
     */
    protected $created = null;
    /**
     * sender optional message = 5
     *
     * @var \Bitrix\Pull\Protobuf\Sender
     */
    protected $sender = null;
    /**
     * Check if 'id' has a value
     *
     * @return bool
     */
    public function hasId()
    {
    }
    /**
     * Get 'id' value
     *
     * @return \Protobuf\Stream
     */
    public function getId()
    {
    }
    /**
     * Set 'id' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setId($value = null)
    {
    }
    /**
     * Check if 'body' has a value
     *
     * @return bool
     */
    public function hasBody()
    {
    }
    /**
     * Get 'body' value
     *
     * @return string
     */
    public function getBody()
    {
    }
    /**
     * Set 'body' value
     *
     * @param string $value
     */
    public function setBody($value = null)
    {
    }
    /**
     * Check if 'expiry' has a value
     *
     * @return bool
     */
    public function hasExpiry()
    {
    }
    /**
     * Get 'expiry' value
     *
     * @return int
     */
    public function getExpiry()
    {
    }
    /**
     * Set 'expiry' value
     *
     * @param int $value
     */
    public function setExpiry($value = null)
    {
    }
    /**
     * Check if 'created' has a value
     *
     * @return bool
     */
    public function hasCreated()
    {
    }
    /**
     * Get 'created' value
     *
     * @return int
     */
    public function getCreated()
    {
    }
    /**
     * Set 'created' value
     *
     * @param int $value
     */
    public function setCreated($value = null)
    {
    }
    /**
     * Check if 'sender' has a value
     *
     * @return bool
     */
    public function hasSender()
    {
    }
    /**
     * Get 'sender' value
     *
     * @return \Bitrix\Pull\Protobuf\Sender
     */
    public function getSender()
    {
    }
    /**
     * Set 'sender' value
     *
     * @param \Bitrix\Pull\Protobuf\Sender $value
     */
    public function setSender(\Bitrix\Pull\Protobuf\Sender $value = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}