<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : response.proto
 */
/**
 * Protobuf message : OutgoingMessagesResponse
 */
class OutgoingMessagesResponse extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * messages repeated message = 1
     *
     * @var \Protobuf\Collection<\Bitrix\Pull\Protobuf\OutgoingMessage>
     */
    protected $messages = null;
    /**
     * Check if 'messages' has a value
     *
     * @return bool
     */
    public function hasMessagesList()
    {
    }
    /**
     * Get 'messages' value
     *
     * @return \Protobuf\Collection<\Bitrix\Pull\Protobuf\OutgoingMessage>
     */
    public function getMessagesList()
    {
    }
    /**
     * Set 'messages' value
     *
     * @param \Protobuf\Collection<\Bitrix\Pull\Protobuf\OutgoingMessage> $value
     */
    public function setMessagesList(\Protobuf\Collection $value = null)
    {
    }
    /**
     * Add a new element to 'messages'
     *
     * @param \Bitrix\Pull\Protobuf\OutgoingMessage $value
     */
    public function addMessages(\Bitrix\Pull\Protobuf\OutgoingMessage $value)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}