<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : request.proto
 */
/**
 * Protobuf message : RequestBatch
 */
class RequestBatch extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * requests repeated message = 1
     *
     * @var \Protobuf\Collection<\Bitrix\Pull\Protobuf\Request>
     */
    protected $requests = null;
    /**
     * Check if 'requests' has a value
     *
     * @return bool
     */
    public function hasRequestsList()
    {
    }
    /**
     * Get 'requests' value
     *
     * @return \Protobuf\Collection<\Bitrix\Pull\Protobuf\Request>
     */
    public function getRequestsList()
    {
    }
    /**
     * Set 'requests' value
     *
     * @param \Protobuf\Collection<\Bitrix\Pull\Protobuf\Request> $value
     */
    public function setRequestsList(\Protobuf\Collection $value = null)
    {
    }
    /**
     * Add a new element to 'requests'
     *
     * @param \Bitrix\Pull\Protobuf\Request $value
     */
    public function addRequests(\Bitrix\Pull\Protobuf\Request $value)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}