<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : response.proto
 */
/**
 * Protobuf message : Response
 */
class Response extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * outgoingMessages optional message = 1
     *
     * @var \Bitrix\Pull\Protobuf\OutgoingMessagesResponse
     */
    protected $outgoingMessages = null;
    /**
     * channelStats optional message = 2
     *
     * @var \Bitrix\Pull\Protobuf\ChannelStatsResponse
     */
    protected $channelStats = null;
    /**
     * serverStats optional message = 3
     *
     * @var \Bitrix\Pull\Protobuf\JsonResponse
     */
    protected $serverStats = null;
    /**
     * Check if 'outgoingMessages' has a value
     *
     * @return bool
     */
    public function hasOutgoingMessages()
    {
    }
    /**
     * Get 'outgoingMessages' value
     *
     * @return \Bitrix\Pull\Protobuf\OutgoingMessagesResponse
     */
    public function getOutgoingMessages()
    {
    }
    /**
     * Set 'outgoingMessages' value
     *
     * @param \Bitrix\Pull\Protobuf\OutgoingMessagesResponse $value
     */
    public function setOutgoingMessages(\Bitrix\Pull\Protobuf\OutgoingMessagesResponse $value = null)
    {
    }
    /**
     * Check if 'channelStats' has a value
     *
     * @return bool
     */
    public function hasChannelStats()
    {
    }
    /**
     * Get 'channelStats' value
     *
     * @return \Bitrix\Pull\Protobuf\ChannelStatsResponse
     */
    public function getChannelStats()
    {
    }
    /**
     * Set 'channelStats' value
     *
     * @param \Bitrix\Pull\Protobuf\ChannelStatsResponse $value
     */
    public function setChannelStats(\Bitrix\Pull\Protobuf\ChannelStatsResponse $value = null)
    {
    }
    /**
     * Check if 'serverStats' has a value
     *
     * @return bool
     */
    public function hasServerStats()
    {
    }
    /**
     * Get 'serverStats' value
     *
     * @return \Bitrix\Pull\Protobuf\JsonResponse
     */
    public function getServerStats()
    {
    }
    /**
     * Set 'serverStats' value
     *
     * @param \Bitrix\Pull\Protobuf\JsonResponse $value
     */
    public function setServerStats(\Bitrix\Pull\Protobuf\JsonResponse $value = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}