<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : response.proto
 */
/**
 * Protobuf message : ResponseBatch
 */
class ResponseBatch extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * responses repeated message = 1
     *
     * @var \Protobuf\Collection<\Bitrix\Pull\Protobuf\Response>
     */
    protected $responses = null;
    /**
     * Check if 'responses' has a value
     *
     * @return bool
     */
    public function hasResponsesList()
    {
    }
    /**
     * Get 'responses' value
     *
     * @return \Protobuf\Collection<\Bitrix\Pull\Protobuf\Response>
     */
    public function getResponsesList()
    {
    }
    /**
     * Set 'responses' value
     *
     * @param \Protobuf\Collection<\Bitrix\Pull\Protobuf\Response> $value
     */
    public function setResponsesList(\Protobuf\Collection $value = null)
    {
    }
    /**
     * Add a new element to 'responses'
     *
     * @param \Bitrix\Pull\Protobuf\Response $value
     */
    public function addResponses(\Bitrix\Pull\Protobuf\Response $value)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}