<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : sender.proto
 */
/**
 * Protobuf enum : SenderType
 */
class SenderType extends \Protobuf\Enum
{
    /**
     * UNKNOWN = 0
     */
    const UNKNOWN_VALUE = 0;
    /**
     * CLIENT = 1
     */
    const CLIENT_VALUE = 1;
    /**
     * BACKEND = 2
     */
    const BACKEND_VALUE = 2;
    /**
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected static $UNKNOWN = null;
    /**
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected static $CLIENT = null;
    /**
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected static $BACKEND = null;
    /**
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function UNKNOWN()
    {
    }
    /**
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function CLIENT()
    {
    }
    /**
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function BACKEND()
    {
    }
    /**
     * @param int $value
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public static function valueOf($value)
    {
    }
}