<?php

namespace Bitrix\Pull\Protobuf;

/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : sender.proto
 */
/**
 * Protobuf message : Sender
 */
class Sender extends \Protobuf\AbstractMessage
{
    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;
    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;
    /**
     * type optional enum = 1
     *
     * @var \Bitrix\Pull\Protobuf\SenderType
     */
    protected $type = null;
    /**
     * id optional bytes = 2
     *
     * @var \Protobuf\Stream
     */
    protected $id = null;
    /**
     * Check if 'type' has a value
     *
     * @return bool
     */
    public function hasType()
    {
    }
    /**
     * Get 'type' value
     *
     * @return \Bitrix\Pull\Protobuf\SenderType
     */
    public function getType()
    {
    }
    /**
     * Set 'type' value
     *
     * @param \Bitrix\Pull\Protobuf\SenderType $value
     */
    public function setType(\Bitrix\Pull\Protobuf\SenderType $value = null)
    {
    }
    /**
     * Check if 'id' has a value
     *
     * @return bool
     */
    public function hasId()
    {
    }
    /**
     * Get 'id' value
     *
     * @return \Protobuf\Stream
     */
    public function getId()
    {
    }
    /**
     * Set 'id' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setId($value = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
    }
    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function clear()
    {
    }
    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
    }
}